### ISSUE TITLE
Springloaded 1.2.2 and 1.2.3 not pushed to central maven repo

### ISSUE THREAD

**Issue by lazee** [spring-projects/spring-loaded#115]
Why isn't 1.2.2.RELEASE and 1.2.3.RELEASE pushed to the Central maven repo?

http://search.maven.org/#browse%7C-1892384460

**Comment by aclement** [comment]
I pressed the same buttons I always press to release it but for some reason they only made it as far as the spring maven repo. I will look at it when I get some time. My primary concern was grails and they were happy to take it from the spring repo.

**Comment by dlvenable** [comment]
Hello @aclement, do you have an estimate on when these versions will be available in Maven Central? We are experiencing the problem reported in issue #98 and would like the fix supplied.

**Comment by aclement** [comment]
1.2.3.RELEASE is now in central: http://search.maven.org/#artifactdetails%7Corg.springframework%7Cspringloaded%7C1.2.3.RELEASE%7Cjar

Sorry for the delay. I had to eventually contact jfrog support about why the promotion process to central wasn't working and they sorted it out.
