### ISSUE TITLE
spring-loaded does not support the @RequestMapping annotation!

### ISSUE THREAD

**Issue by zhang13690** [spring-projects/spring-loaded#200]
I used the SpringMVC framework. If I add a request method with the '@RequestMapping' annotaion, the spring-loaded  dose not work.

**Comment by lanmolsz** [comment]
You need to restart your application

**Comment by zhang13690** [comment]
@lanmolsz, The purpose of spring-loaded is , we do not neet to restart applications.

**Comment by lanmolsz** [comment]
看你也是中国人，正经回答一下吧。
先抱歉一下，感觉自己用英文大段的来描述这些原因对我来说比较困难。
----
spring-loaded不是不支持`@RequestMapping`注解。而是我们需要先大致搞明白spring-mvc的初始化过程和路由逻辑。对于程序来讲，你所有的类信息都可以看作程序的一些元数据，spring-mvc在启动的时候通过反射获取到这些元数据，并将其缓存成某种数据结构，需要注意的是，前面这种动作只会在启动的时候执行一次，后续处理请求路由到你的业务方法都是通过取读取这个缓存的数据，反射调用。

很显然，你后面添加的`@RequestMapping`并不会触发spring-mvc的初始化操作，那么新添加的代码无法生效也不足为奇了。

如何解决？其实wiki里面是说过的，并且说的很明确。
你可以通过编写一个插件，实现`org.springsource.loaded.ReloadEventProcessorPlugin`，并注册`SpringLoadedPreProcessor.registerGlobalPlugin(plugin)`，然后，这个插件就会在spring-loaded重新加载时被调用了。

**Comment by zhang13690** [comment]
@lanmolsz 感谢你细致的解答，小生佩服。
