### ISSUE TITLE
Stream with lambda fails

### ISSUE THREAD

**Issue by bep** [spring-projects/spring-loaded#82]
I assume this is not implemented, so lets call it a feature request.

I have a class with a a construction like `items.stream().map(n -> foo.m(n)).collect(Collectors.toList())` that fails on reload.

I get this:

```
java.lang.IllegalStateException: The type registry TypeRegistry(id=269223509,loader=sun.misc.Launcher$AppClassLoader) does not know about type id 163
	at org.springsource.loaded.TypeRegistry.getReloadableType(TypeRegistry.java:1694)
	at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1578)
```
I tried to create a breaking test for it, see bjornerik/spring-loaded@58b7a0be09db30aa3368480b074b6af47f0ebd3d and the failing test `streamWithLambda()`.

I get:

```
java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: no such method: basic.StreamA$$E002.lambda$run$26(Foo,Integer)Integer/invokeStatic
```
Also when invoked virtually (see `streamWithLambdaInvokedVirtually()`):
```
Caused by: java.lang.IllegalStateException: nyi 9
	at org.springsource.loaded.support.Java8.callLambdaMetaFactory(Java8.java:150)
	at org.springsource.loaded.support.Java8.emulateInvokeDynamic(Java8.java:94)
	... 38 more
```

Which obviously means this is not implemented.

My environment:
```
Linux bep-laptop 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
```

**Comment by danhyun** [comment]
+1 for this please

**Comment by Elisabeth-Engel** [comment]
+1 as well

**Comment by ilx** [comment]
+1

**Comment by ajaegle** [comment]
+1
just ran into this, too.

**Comment by aclement** [comment]
I added support for case 9 (H_INVOKEINTERFACE). I'm not totally happy with it because I'm a bit rusty on that area of the code but it passes the testcase from above. The other failing test in that group of test cases was due to the test harness, it wasn't fully rewriting the bootstrap method arguments, so left behind a reference to a non existent type. I've fixed that too.

**Comment by aclement** [comment]
thanks for tests!
