### ISSUE TITLE
How can I use this with maven-tomcat7-plugin?

### ISSUE THREAD

**Issue by ahmedmohiduet** [spring-projects/spring-loaded#97]
I put this in my pom.xml. But it seems to be not working with "mvn tomcat7:run"
```javascript
<plugin>
				<groupId>org.apache.tomcat.maven</groupId>
				<artifactId>tomcat7-maven-plugin</artifactId>
				<version>2.0</version>
				<configuration>
					<server>tomcat-development-server</server>
					<port>9966</port>
					<path>/vudy</path>
					<systemProperties>
						<JAVA_OPTS>-javaagent:/usr/local/springtools/springloaded-1.2.1.RELEASE.jar -noverify</JAVA_OPTS>
					</systemProperties>
				</configuration>
			</plugin>
```

Am I missing something here?
Any suggestions or documentation?

**Comment by miixel2** [comment]
Hi @ahmedmohiduet, 
    I've done this way and it' been worked perfectly.

1. Create tomcat context xml file to configure virtual web loader. 
 I kept file in this location <project.baseDir>/tomcat/context.xml 
The content of context is as following.
<?xml version="1.0" encoding="UTF-8"?>
<Context>
    <Resources className="org.apache.naming.resources.VirtualDirContext"
               extraResourcePaths="/=${project.build.directory}/${project.build.finalName}">
    </Resources>
    <Loader searchVirtualFirst="true" className="org.apache.catalina.loader.VirtualWebappLoader"
            virtualClasspath="${project.build.outputDirectory}"/>
</Context>

2. In POM file, at the tomcat7 plugin configuration. I added the execution section like this.
           <executions>
                    <execution>
                        <id>run-embedded</id>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <phase>pre-integration-test</phase>
                        <configuration>
                            <useSeparateTomcatClassLoader>true</useSeparateTomcatClassLoader>
                            <contextFile>${project.basedir}/tomcat/context.xml</contextFile>
                        </configuration>
                    </execution>
                </executions>
3.  Run your application (with springloaded javaagent);
    mvn clean package pre-integration-test

I'm not quite sure why it's not working on tomcat7:run.

Hope this help,
Thanakit

**Comment by ahmedmohiduet** [comment]
Thanks Thanakit! I will definitely try it

**Comment by miixel2** [comment]
@ahmedmohiduet  I've update the answer to be readable. Sorry for my previous mistake. I didn't see that the xml show incorrectly. :p

**Comment by ahmedmohiduet** [comment]
Thanks for the correction Thanakit! :)
